name: Build

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Images for dev
      run: |
          docker build -t test .
          docker run -d -p 80:80 
          docker ps
    - uses: azure/container-scan@v0
      with:
        image-name: test
     
